New-SPWeb  -Url   http://sppilot.nibib.nih.gov/sites/OD/ES -Template "STS#0" -AddToTopNav -UniquePermissions -UseParentTopNav -Name "Executive Share" -errorAction silently continue
New-SPWeb  -Url  http://sppilot.nibib.nih.gov/sites/ORA/OCM -Template "STS#0" -AddToTopNav -UniquePermissions -UseParentTopNav -Name "Office of Committee Management" -errorAction silently continue
New-SPWeb  -Url  http://sppilot.nibib.nih.gov/sites/ORA/OGM -Template "STS#0" -AddToTopNav -UniquePermissions -UseParentTopNav -Name "Office of Grants Management" -errorAction silently continue
New-SPWeb  -Url   http://sppilot.nibib.nih.gov/sites/ORA/OSPE -Template "STS#0" -AddToTopNav -UniquePermissions -UseParentTopNav -Name "Office of Strategic Partnership and Evaluation" -errorAction silently continue
New-SPWeb  -Url  http://sppilot.nibib.nih.gov/sites/ORA/OSR -Template "STS#0" -AddToTopNav -UniquePermissions -UseParentTopNav -Name "Office of Scientific Research" -errorAction silently continueNew-SPWeb  -Url  http://sppilot.nibib.nih.gov/sites/ESP/DAST -Template "STS#0" -AddToTopNav -UniquePermissions -UseParentTopNav -Name "Division of Applied Science and Technology" -ErrorAction silentlycontinue
New-SPWeb  -Url  http://sppilot.nibib.nih.gov/sites/ESP/DDST -Template "STS#0" -AddToTopNav -UniquePermissions -UseParentTopNav -Name "Division of Discovery Science and Technology" -ErrorAction silentlycontinue
New-SPWeb  -Url  http://sppilot.nibib.nih.gov/sites/ESP/DHIT  -Template "STS#0" -AddToTopNav -UniquePermissions -UseParentTopNav -Name "Division of Health Information Technology" -ErrorAction silentlycontinue
New-SPWeb  -Url  http://sppilot.nibib.nih.gov/sites/ESP/DIDT  -Template "STS#0" -AddToTopNav -UniquePermissions -UseParentTopNav -Name "Division of Interdisciplinary Training" -ErrorAction silentlycontinue
New-SPWeb  -Url  http://sppilot.nibib.nih.gov/sites/ESP/ESPOD -Template "STS#0" -AddToTopNav -UniquePermissions -UseParentTopNav -Name "Extramural Science Program - Office of the Director" -ErrorAction silentlycontinue
New-SPWeb  -Url  http://sppilot.nibib.nih.gov/sites/ESP/OPESP  -Template "STS#0" -AddToTopNav -UniquePermissions -UseParentTopNav -Name "Office of Program Evaluation and Strategic Partnerships" -ErrorAction silentlycontinue
New-SPWeb  -Url  http://sppilot.nibib.nih.gov/sites/IRP/BEPS -Template "STS#0" -AddToTopNav -UniquePermissions -UseParentTopNav -Name "Biomedical Engineering and Physical Science Shared Resource Program" -ErrorAction silentlycontinue
New-SPWeb  -Url  http://sppilot.nibib.nih.gov/sites/IRP/BEPS/em -Template "STS#0" -AddToTopNav -UniquePermissions -UseParentTopNav -Name "Electron Microscopy" -ErrorAction silentlycontinue
New-SPWeb  -Url  http://sppilot.nibib.nih.gov/sites/IRP/BEPS/iit -Template "STS#0" -AddToTopNav -UniquePermissions -UseParentTopNav -Name "Infrared Imaging and Thermometry" -ErrorAction silentlycontinue
New-SPWeb  -Url  http://sppilot.nibib.nih.gov/sites/IRP/BEPS/mai  -Template "STS#0" -AddToTopNav -UniquePermissions -UseParentTopNav -Name "Micro Analytical Immunochemistry" -ErrorAction silentlycontinue
New-SPWeb  -Url  http://sppilot.nibib.nih.gov/sites/IRP/BEPS/mm  -Template "STS#0" -AddToTopNav -UniquePermissions -UseParentTopNav -Name "Micro-fabrication and Microfluidics " -ErrorAction silentlycontinue
New-SPWeb  -Url  http://sppilot.nibib.nih.gov/sites/IRP/BEPS/qmmi  -Template "STS#0" -AddToTopNav -UniquePermissions -UseParentTopNav -Name "Quantitative Methods for Macromolecular Interactions" -ErrorAction silentlycontinue
New-SPWeb  -Url  http://sppilot.nibib.nih.gov/sites/IRP/BEPS/spm  -Template "STS#0" -AddToTopNav -UniquePermissions -UseParentTopNav -Name "Scanning Probe Microscopy" -ErrorAction silentlycontinue
New-SPWeb  -Url  http://sppilot.nibib.nih.gov/sites/IRP/biophotonics -Template "STS#0" -AddToTopNav -UniquePermissions -UseParentTopNav -Name "Biophotonics" -ErrorAction silentlycontinue
New-SPWeb  -Url  http://sppilot.nibib.nih.gov/sites/IRP/HROI -Template "STS#0" -AddToTopNav -UniquePermissions -UseParentTopNav -Name "High Resolution Optical Imaging" -ErrorAction silentlycontinue
New-SPWeb  -Url  http://sppilot.nibib.nih.gov/sites/IRP/LCIMB -Template "STS#0" -AddToTopNav -UniquePermissions -UseParentTopNav -Name "Laboratory of Cellular Imaging and Macromolecular Biophysics" -ErrorAction silentlycontinue
New-SPWeb  -Url  http://sppilot.nibib.nih.gov/sites/IRP/LCIMB/dma -Template "STS#0" -AddToTopNav -UniquePermissions -UseParentTopNav -Name "Dynamics of Macromolecular Assembly" -ErrorAction silentlycontinue
New-SPWeb  -Url  http://sppilot.nibib.nih.gov/sites/IRP/LCIMB/nfs  -Template "STS#0" -AddToTopNav -UniquePermissions -UseParentTopNav -Name "Nano instrumentation and Force Spectroscopy" -ErrorAction silentlycontinue
New-SPWeb  -Url  http://sppilot.nibib.nih.gov/sites/IRP/LCIMB/cssf -Template "STS#0" -AddToTopNav -UniquePermissions -UseParentTopNav -Name "The Cellular and Supra-molecular Structure and Function (CSSF) Section" -ErrorAction silentlycontinue
New-SPWeb  -Url  http://sppilot.nibib.nih.gov/sites/IRP/LOMIN -Template "STS#0" -AddToTopNav -UniquePermissions -UseParentTopNav -Name "Laboratory of Molecular Imaging and Nano medicine" -ErrorAction silentlycontinue
New-SPWeb  -Url  http://sppilot.nibib.nih.gov/sites/IRP/LOMIN/bmi -Template "STS#0" -AddToTopNav -UniquePermissions -UseParentTopNav -Name "Biological Molecular Imaging" -ErrorAction silentlycontinue
New-SPWeb  -Url  http://sppilot.nibib.nih.gov/sites/IRP/LOMIN/chem -Template "STS#0" -AddToTopNav -UniquePermissions -UseParentTopNav -Name "Chemistry and Radiochemistry Section " -ErrorAction silentlycontinue
New-SPWeb  -Url  http://sppilot.nibib.nih.gov/sites/IRP/LOMIN/tns  -Template "STS#0" -AddToTopNav -UniquePermissions -UseParentTopNav -Name "Theranostic Nano medicine Section" -ErrorAction silentlycontinue
New-SPWeb  -Url  http://sppilot.nibib.nih.gov/sites/IRP/MBIL -Template "STS#0" -AddToTopNav -UniquePermissions -UseParentTopNav -Name "Molecular Biomedical Imaging Laboratory " -ErrorAction silentlycontinue
New-SPWeb  -Url  http://sppilot.nibib.nih.gov/sites/OAM/AO -Template "STS#0" -AddToTopNav -UniquePermissions -UseParentTopNav -Name "Administrative Office" -ErrorAction silentlycontinue
New-SPWeb  -Url   http://sppilot.nibib.nih.gov/sites/OAM/EO -Template "STS#0" -AddToTopNav -UniquePermissions -UseParentTopNav -Name "Executive Office" -ErrorAction silentlycontinue
New-SPWeb  -Url  http://sppilot.nibib.nih.gov/sites/OAM/ITO  -Template "STS#0" -AddToTopNav -UniquePermissions -UseParentTopNav -Name "Information Technology Office" -ErrorAction silentlycontinue
New-SPWeb  -Url  http://sppilot.nibib.nih.gov/sites/OAM/ITO/lcgs  -Template "STS#0" -AddToTopNav -UniquePermissions -UseParentTopNav -Name "LCG Staff Site" -ErrorAction silentlycontinue
New-SPWeb  -Url  http://sppilot.nibib.nih.gov/sites/OAM/ITO/VIR  -Template "STS#0" -AddToTopNav -UniquePermissions -UseParentTopNav -Name "Virtual Infrastructure Re-design" -ErrorAction silentlycontinue
New-SPWeb  -Url  http://sppilot.nibib.nih.gov/sites/OAM/ITO/webteam  -Template "STS#0" -AddToTopNav -UniquePermissions -UseParentTopNav -Name "Web Team" -ErrorAction silentlycontinue
New-SPWeb  -Url   http://sppilot.nibib.nih.gov/sites/OAM/ITO/webteam/Public-web -Template "STS#0" -AddToTopNav -UniquePermissions -UseParentTopNav -Name "Public Web" -ErrorAction silentlycontinue
New-SPWeb  -Url  http://sppilot.nibib.nih.gov/sites/OAM/OFM   -Template "STS#0" -AddToTopNav -UniquePermissions -UseParentTopNav -Name "Office of Financial Management" -ErrorAction silentlycontinue
New-SPWeb  -Url   http://sppilot.nibib.nih.gov/sites/OAM/OSPC -Template "STS#0" -AddToTopNav -UniquePermissions -UseParentTopNav -Name "​​​Office of Science Policy and Communications" -ErrorAction silentlycontinue